name: cs349
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - colorama=0.4.6
  - contourpy=1.3.1
  - cycler=0.12.1
  - exceptiongroup=1.2.2
  - fairlearn=0.12.0
  - fonttools=4.57.0
  - freetype=2.13.3
  - iniconfig=2.0.0
  - joblib=1.4.2
  - kiwisolver=1.4.7
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=20.1.2
  - libdeflate=1.23
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsqlite=3.49.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=20.1.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - munkres=1.1.4
  - ncurses=6.5
  - numpy=2.2.0
  - openjpeg=2.5.3
  - openssl=3.4.1
  - packaging=24.2
  - pandas=2.2.3
  - pillow=11.1.0
  - pip=25.0.1
  - pluggy=1.5.0
  - pthread-stubs=0.4
  - pyparsing=3.2.3
  - pytest=8.3.4
  - python=3.13.2
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2024.1
  - qhull=2020.2
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - setuptools=78.1.0
  - six=1.17.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.4.2
  - tzdata=2025b
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zstd=1.5.7
  - pip:
      - cloudpickle==3.1.1
      - farama-notifications==0.0.4
      - gymnasium==1.1.1
      - seaborn==0.13.2
      - tabulate==0.9.0
      - typing-extensions==4.13.2
prefix: /Users/zihanwang/miniconda3/envs/cs349
